[tool.poetry]
name = "dangerzone"
version = "0.3.2"
description = "Take potentially dangerous PDFs, office documents, or images and convert them to safe PDFs"
authors = ["Micah Lee <micah.lee@theintercept.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
click = "*"
appdirs = "*"
PySide2 = "5.15.2"
colorama = "*"
cx_freeze = {version = "*", platform = "win32"}
pywin32 = {version = "*", platform = "win32"}
pyxdg = {version = "*", platform = "linux"}
pyinstaller = {version = "*", platform = "darwin"}
strip-ansi = {version = "*", platform = "darwin"}

[tool.poetry.dev-dependencies]
setuptools = {version = "*", platform = "win32"}
black = "*"
isort = "*"
mypy = "*"
PySide2-stubs = "*"
strip-ansi = "*"
pytest = "^7.1.2"
pytest-xdist = "^2.5.0"

[tool.poetry.scripts]
dangerzone = 'dangerzone:main'
dangerzone-container = 'dangerzone:main'
dangerzone-cli = 'dangerzone:main'

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
